name: Build Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    
    - name: Upload DLL References
      uses: actions/upload-artifact@v4
      with:
        name: missing-dlls
        path: References
        
    - name: Wait for DLLs
      run: |
        echo "Please upload the required DLLs to the References folder in the repository"
        echo "Then re-run this workflow manually from the Actions tab"
      if: ${{ github.event_name != 'workflow_dispatch' }}
      
    - name: Build
      run: dotnet build -c Release
      if: ${{ success() && hashFiles('References/*.dll') != '' }}
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WeaponAbilityCustomizerMod
        path: bin/Release/net6.0/WeaponAbilityCustomizerMod.dll
      if: ${{ success() && hashFiles('References/*.dll') != '' }}
